# Site settings
title: 'yux.ch - Passionate Coding'
email: raffael+website@yux.ch
author: 'Raffael Schmid'
description: "Website of Raffael Schmid"
baseurl: ""
url: "http://yux.ch"
twitter_username: rafschmid
github_username:  luxflux
excerpt_separator: "<!-- more -->"

# Build settings
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title.html"
exclude:
  - CNAME
  - config
  - vendor
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - assets

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
